### ISSUE TITLE
SP points to last-1 instead of last push

### ISSUE THREAD

**Issue by Stokpan** [FunIsDangerous/8085_emulator#10]
initial SP = 0000
run:
```
MVI A,F0H
INR A
PUSH PSW
HLT
```
SP = FFFD, it should be FFFE instead.

SP isn't pointing to the address containing the last PUSHed byte but rather the next available one. This is an error, according to Intel's specification (see 3-44, 3-45) it should be pointing to the address of the last one.

**Comment by FanisDeligiannis** [comment]
Nice catch! In order to adhere to that, I'm probably going to start the SP at address FFFE. It *could* still start at FFFF, but since every PUSH is pushing 16 bits, I'd like to keep those aligned nicely in the memory. 

That way:

If SP=FFFE, the stack is empty
SP will always pointsto the last added data.
If SP > FFFE, you've popped an empty stack (which will, in the future, notify you and give you a warning).

Does that sound okay?

**Comment by Stokpan** [comment]
Sounds perfect, and FFFE is the starting address of some old, respected but outdated simulators.

**Comment by FanisDeligiannis** [comment]
Fixed as of edc7bc007c253a4d4482d7cf745677e50b7ce663.
Thank you!
